os: linux
dist: xenial

services:
  - mysql

language: php

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.4
      env: PHPCS=1
  include:
    - php: 7.4
      env: PHPCS=1
    - php: 7.4
      env: PHPUNIT_VERSION=7.5.20
    - php: 7.3
      env: PHPUNIT_VERSION=7.5.20
    - php: 7.2
      env: PHPUNIT_VERSION=7.5.20
    - php: 7.1
      env: PHPUNIT_VERSION=7.5.20
    - php: 7.0
      env: PHPUNIT_VERSION=6.5.14
    - php: 5.6
      env: PHPUNIT_VERSION=5.7.27

before_script:
  - |
    if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      phpenv config-rm xdebug.ini
    else
      echo \"xdebug.ini does not exist\"
    fi
  - |
    if [ "$PHPCS" == "1" ]; then
      (cd tests && composer install)
    else
      bash bin/install-wp-tests.sh wordpress_test root '' localhost latest
      wget https://phar.phpunit.de/phpunit-$PHPUNIT_VERSION.phar -O /tmp/phpunit
      chmod +x /tmp/phpunit
    fi
script:
  - |
    if [ "$PHPCS" == "1" ]; then
      tests/vendor/bin/phpcs
    else
      /tmp/phpunit
      WP_MULTISITE=1 /tmp/phpunit
    fi
